# Welcome to Jekyll!

# Website settings
title: "李鹏飞"
#介绍
description: "LPF's blog,use Jekyll and github pages."
#关键字
keywords: "LPF,blog,github,gh-pages"

baseurl: "/"
#项目地址
url: "https://LPengFei.github.io"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'https://LPengFei.github.io'

# author
author:
  name: '李鹏飞'
  first_name: '李'
  last_name: '鹏飞'
  email: '289132718@qq.com'
  github_username: 'LPengFei'
  head_img: 'static/img/landing/lpf.jpg'

# social link
jingyu:

  first_name: '李'
  last_name: '鹏飞'
  description: 'IT、JAVA、C#、MySQL、Oracle'
  link: 'https://LPengFei.github.io'
  email: '289132718@qq.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: 李鹏飞
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
